"""initial migration

Revision ID: 1724f6c29a14
Revises: 
Create Date: 2026-04-11 14:58:07.079424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1724f6c29a14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caso_exito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('imagen', sa.Text(), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('resultados', sa.Text(), nullable=True),
    sa.Column('autor_testimonio', sa.String(length=100), nullable=True),
    sa.Column('cargo_testimonio', sa.String(length=100), nullable=True),
    sa.Column('texto_testimonio', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('componente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('subtitulo', sa.String(length=200), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('socio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('imagen', sa.Text(), nullable=False),
    sa.Column('whatsapp', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('componente_afectado', sa.String(length=100), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    op.drop_table('usuario')
    op.drop_table('socio')
    op.drop_table('componente')
    op.drop_table('caso_exito')
    # ### end Alembic commands ###
